### ISSUE TITLE
pyqt5 no exist in download

### ISSUE THREAD

**Issue by Redrichmond** [viktorvillalobos/CompaniesHouse#1]
File "D:\companies house project\CompaniesHouse python\main.py", line 13, in <module>
    from PyQt5.QtCore import *
ModuleNotFoundError: No module named 'PyQt5'
# 

**author** = "Victor H. Villalobos B."
**copyright** = "Copyright 2015"

import sys
import subprocess
import os
import configparser

from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from wMain import Ui_MainWindow
from configuration import wConfiguration
from importer import Importer
from about import wAbout

class wMain(QMainWindow, Ui_MainWindow):
    def **init**(self, parent=None):
        super(wMain, self).**init**(parent)
        self.setupUi(self)
        self.statusbar.showMessage('Utility for CompaniesHouse.gov.uk import')
        self.updateApiKey()
        if getattr(sys, 'frozen', False):

**Comment by viktorvillalobos** [comment]
@Redrichmond You need to install PyQt5 bro.
